logging:
  level:
    ninja:
      skyrocketing:
        fuyao:
          bot:
            mapper: debug
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*/*.xml
  type-aliases-package: ninja.skyrocketing.fuyao.bot.pojo.*
pagehelper:
  helperDialect: mysql
  params: count=countSql
  reasonable: true
  supportMethodsArguments: true
spring:
  datasource:
    url: ''
    username: ''
    password: ''
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
      filters: stat,wall
      initial-size: 5
      max-active: 20
      max-evictable-idle-time-millis: 400000
      max-open-prepared-statements: -1
      max-wait: 3000
      min-evictable-idle-time-millis: 300000
      min-idle: 5
      pool-prepared-statements: false
      stat-view-servlet:
        login-password: 123
        login-username: admin
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      use-global-data-source-stat: true
      validation-query: SELECT 1 FROM DUAL
      web-stat-filter:
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
    initial-size: 5
    max-idle: 10
    max-wait: 10000
    min-idle: 5
    type: com.alibaba.druid.pool.DruidDataSource
  devtools:
    add-properties: false
